name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "* * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Auto green
        run: |
          git config --local user.email "3040964170@qq.com"
          git config --local user.name "Nya-Cow"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Nya-Cow/Green.git
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend stay"
          git push
